### ISSUE TITLE
Which repo should I need to test

### ISSUE THREAD

**Issue by zhuangbility111** [fujitsu/oneDNN#66]
Hello! Now I want to test the performance on Fugaku, but I found that there are two repo, `fujitsu/oneDNN` and `oneapi/oneDNN`. So Could you please tell me which repo should I need to test?

**Comment by kawakami-k** [comment]
Hi, @zhuangbility111 
The two source codes have almost the same performance when run on Fugaku. Since RIKEN provides pre-built oneDNN for Fugaku users, I think it is easy and good to use it. The pre-build oneDNN is based on `fujitsu/oneDNN`.

**Comment by zhuangbility111** [comment]
OK. Thank you very much!

**Comment by zhuangbility111** [comment]
Hi. @kawakami-k  
Sorry I have another problem.. Whether the pre-build oneDNN is used as the backend of Pytorch on Fugaku?

**Comment by kawakami-k** [comment]
RIKEN has provided pre-build Pytorch and oneDNN `(fujitsu/oneDNN)` as the backend for Fugaku users.

**Comment by zhuangbility111** [comment]
Ok.. Actually I am testing the performance of `torch.bmm()` on Fugaku. Is that possible the `torch.bmm()` we call falls back to `matmul()` in fujitsu/oneDNN?

**Comment by kawakami-k** [comment]
Sorry, I'm not sure if it's supported. RIKEN has provided `fujitsu/oneDNN` which is linked Fujitsu SSL-II library.  SSL-II includes BLAS compatible functions optimized for A64FX CPU used in Fugaku.  You may be able to call the matrix multiplication function of SSL-II via oneDNN.

**Comment by zhuangbility111** [comment]
thanks! if I want to compile this repo and link it with Fujitsu SSL-II library as BLAS_LIBRARY, which cmake flags should I need to set? Now i can't access the pre-built oneDNN on Fugaku since I and my colleagues don't know how to access it..

**Comment by zhuangbility111** [comment]
```
-- The C compiler identification is Clang 7.1.0
-- The CXX compiler identification is Clang 7.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/FJSVxtclanga/tcsds-1.2.33/bin/fcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/FJSVxtclanga/tcsds-1.2.33/bin/FCC - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found Git: /usr/bin/git (found version "2.27.0") 
-- Checking for [fjlapackexsve]
--   Library fjlapackexsve: /opt/FJSVxtclanga/tcsds-1.2.33/lib64/libfjlapackexsve.so
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found a library with BLAS API (ssl2).
-- Found XED: /vol0004/ra000012/a04453/oneDNN_new_version/oneDNN/src/cpu/aarch64/xbyak_translator_aarch64/translator/third_party/build_xed_aarch64/kits/xed/include  
-- Found XBYAK_AARCH64: /vol0004/ra000012/a04453/oneDNN_new_version/oneDNN/src/cpu/aarch64  
-- Found XBYAK_TRANSLATOR_AARCH64: /vol0004/ra000012/a04453/oneDNN_new_version/oneDNN/src/cpu/aarch64/xbyak_translator_aarch64/translator/include  
-- Xed Library: /vol0004/ra000012/a04453/oneDNN_new_version/oneDNN/src/cpu/aarch64/xbyak_translator_aarch64/translator/third_party/build_xed_aarch64/kits/xed/lib/libxed.so
-- Xbyak_aarch64 Library: /vol0004/ra000012/a04453/oneDNN_new_version/oneDNN/src/cpu/aarch64/xbyak_translator_aarch64/translator/third_party/xbyak_aarch64/lib/libxbyak_aarch64.a
-- Xbyak_translator_aarch64 Library: /vol0004/ra000012/a04453/oneDNN_new_version/oneDNN/src/cpu/aarch64/xbyak_translator_aarch64/lib/libxbyak_translator_aarch64.a
-- Primitive cache is enabled
-- Configuring done
-- Generating done
```
whether this means that I have linked it with ssl2 successfully?

**Comment by kawakami-k** [comment]
Sample build instruction is disclosed here.
https://github.com/fujitsu/pytorch/wiki/PyTorch-DNNL_aarch64-build-manual-for-FUJITSU-Software-Compiler-Package-(PyTorch-v1.7.0)

I recommend that you try this instruction. In the process of building Pytorch, oneDNN is also built. I think that the oneDNN built here will be the one with SSL-II linked.

**Comment by kawakami-k** [comment]
> -- Found a library with BLAS API (ssl2).

From your CMake log, I think oneDNN with SSL-II linked will be built.

**Comment by zhuangbility111** [comment]
ok... But I just want to test the performance of a stand-alone oneDNN on fugaku. such as calling the `matmul()` instead of  calling the `torch.bmm()`. According to https://github.com/fujitsu/pytorch/wiki/PyTorch-DNNL_aarch64-build-manual-for-FUJITSU-Software-Compiler-Package-(PyTorch-v1.7.0), can I obtain a stand-alone oneDNN?

**Comment by kawakami-k** [comment]
I see, the following steps should match what you want to do.
https://github.com/fujitsu/oneDNN/blob/2566679ad26e8bd63cc30cc0c9c1662c4f198f4a/.gitlab-ci.yml#L21-L24

**Comment by zhuangbility111** [comment]
It works. Thank you very much!!
