### ISSUE TITLE
Are some tensor operations not performed in parallel?

### ISSUE THREAD

**Issue by zhuangbility111** [fujitsu/oneDNN#67]
# Summary
In recent days i used the torch profiler tools `torch.autograd.profiler` to profile the routines of some deep learning model on Fugaku with pre-built Pytorch 1.7.0, which is supported by oneDNN. I find some interesting phenomenons like that when I incresed the thread number, the elapsed time of `aten::mm()` decreased. But other routines such as `aten::index()` or `aten::index_add_()` listed as following still spent the same time. 

BTW, i control the thread number of torch with `export OMP_NUM_THREADS`.

### the profiling result with 1 thread on Fujitsu a64fx:
------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls   
                            aten::mm        15.55%        2.150s        15.80%        2.185s       2.185ms          1000  
                    aten::index_add_        12.32%        1.704s        12.79%        1.768s       4.421ms           400  
                         aten::empty         7.82%        1.082s         7.82%        1.082s      53.565us         20200  
                         aten::index         5.42%     749.200ms        16.44%        2.274s     710.501us          3200  
                           aten::mul         4.61%     637.007ms         7.10%     982.267ms     491.133us          2000  
                    aten::as_strided         4.49%     621.362ms         4.49%     621.362ms      35.710us         17400  

### the profiling result with 12 threads (one numa node on Fujitsu a64fx):
------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls   
                    aten::index_add_        15.51%        1.706s        16.09%        1.770s       4.424ms           400  
                         aten::empty         7.39%     812.354ms         7.39%     812.354ms      40.216us         20200  
                         aten::index         6.79%     746.807ms        20.87%        2.295s     717.327us          3200  
                    aten::as_strided         5.65%     621.071ms         5.65%     621.071ms      35.694us         17400  
                        aten::stride         4.74%     520.896ms         4.74%     520.896ms      35.678us         14600  
                  aten::scatter_add_         4.27%     469.165ms         5.23%     575.682ms     719.603us           800  
                            aten::mm         4.18%     459.510ms         4.49%     494.311ms     494.311us          1000

**Comment by kawakami-k** [comment]
@zhuangbility111 
Thank you for the report. I am not familiar with ATEN, so the following explanation may be incorrect.

oneDNN and OpenBLAS are  internally multi-threaded using OpenMP. The number of threads can be controlled by OMP_NUM_THREADS. Other implementations used by ATEN are not multithreaded and need to be multithreaded by the caller, which may not be the case with the current PyTorch.
